// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: admin_rpc.proto

package farcaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_SubmitOnChainEvent_FullMethodName        = "/farcaster.AdminService/SubmitOnChainEvent"
	AdminService_SubmitUserNameProof_FullMethodName       = "/farcaster.AdminService/SubmitUserNameProof"
	AdminService_UploadSnapshot_FullMethodName            = "/farcaster.AdminService/UploadSnapshot"
	AdminService_RetryOnchainEvents_FullMethodName        = "/farcaster.AdminService/RetryOnchainEvents"
	AdminService_RetryFnameEvents_FullMethodName          = "/farcaster.AdminService/RetryFnameEvents"
	AdminService_RunOnchainEventsMigration_FullMethodName = "/farcaster.AdminService/RunOnchainEventsMigration"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	SubmitOnChainEvent(ctx context.Context, in *OnChainEvent, opts ...grpc.CallOption) (*OnChainEvent, error)
	SubmitUserNameProof(ctx context.Context, in *UserNameProof, opts ...grpc.CallOption) (*UserNameProof, error)
	UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*Empty, error)
	RetryOnchainEvents(ctx context.Context, in *RetryOnchainEventsRequest, opts ...grpc.CallOption) (*Empty, error)
	RetryFnameEvents(ctx context.Context, in *RetryFnameRequest, opts ...grpc.CallOption) (*Empty, error)
	RunOnchainEventsMigration(ctx context.Context, in *RunOnchainEventsMigrationRequest, opts ...grpc.CallOption) (*Empty, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) SubmitOnChainEvent(ctx context.Context, in *OnChainEvent, opts ...grpc.CallOption) (*OnChainEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEvent)
	err := c.cc.Invoke(ctx, AdminService_SubmitOnChainEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SubmitUserNameProof(ctx context.Context, in *UserNameProof, opts ...grpc.CallOption) (*UserNameProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserNameProof)
	err := c.cc.Invoke(ctx, AdminService_SubmitUserNameProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_UploadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RetryOnchainEvents(ctx context.Context, in *RetryOnchainEventsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_RetryOnchainEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RetryFnameEvents(ctx context.Context, in *RetryFnameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_RetryFnameEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RunOnchainEventsMigration(ctx context.Context, in *RunOnchainEventsMigrationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_RunOnchainEventsMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	SubmitOnChainEvent(context.Context, *OnChainEvent) (*OnChainEvent, error)
	SubmitUserNameProof(context.Context, *UserNameProof) (*UserNameProof, error)
	UploadSnapshot(context.Context, *UploadSnapshotRequest) (*Empty, error)
	RetryOnchainEvents(context.Context, *RetryOnchainEventsRequest) (*Empty, error)
	RetryFnameEvents(context.Context, *RetryFnameRequest) (*Empty, error)
	RunOnchainEventsMigration(context.Context, *RunOnchainEventsMigrationRequest) (*Empty, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) SubmitOnChainEvent(context.Context, *OnChainEvent) (*OnChainEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOnChainEvent not implemented")
}
func (UnimplementedAdminServiceServer) SubmitUserNameProof(context.Context, *UserNameProof) (*UserNameProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitUserNameProof not implemented")
}
func (UnimplementedAdminServiceServer) UploadSnapshot(context.Context, *UploadSnapshotRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSnapshot not implemented")
}
func (UnimplementedAdminServiceServer) RetryOnchainEvents(context.Context, *RetryOnchainEventsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryOnchainEvents not implemented")
}
func (UnimplementedAdminServiceServer) RetryFnameEvents(context.Context, *RetryFnameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryFnameEvents not implemented")
}
func (UnimplementedAdminServiceServer) RunOnchainEventsMigration(context.Context, *RunOnchainEventsMigrationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunOnchainEventsMigration not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_SubmitOnChainEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnChainEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SubmitOnChainEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SubmitOnChainEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SubmitOnChainEvent(ctx, req.(*OnChainEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SubmitUserNameProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNameProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SubmitUserNameProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SubmitUserNameProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SubmitUserNameProof(ctx, req.(*UserNameProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UploadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UploadSnapshot(ctx, req.(*UploadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RetryOnchainEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryOnchainEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RetryOnchainEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RetryOnchainEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RetryOnchainEvents(ctx, req.(*RetryOnchainEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RetryFnameEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RetryFnameEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RetryFnameEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RetryFnameEvents(ctx, req.(*RetryFnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RunOnchainEventsMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunOnchainEventsMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RunOnchainEventsMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RunOnchainEventsMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RunOnchainEventsMigration(ctx, req.(*RunOnchainEventsMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "farcaster.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOnChainEvent",
			Handler:    _AdminService_SubmitOnChainEvent_Handler,
		},
		{
			MethodName: "SubmitUserNameProof",
			Handler:    _AdminService_SubmitUserNameProof_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _AdminService_UploadSnapshot_Handler,
		},
		{
			MethodName: "RetryOnchainEvents",
			Handler:    _AdminService_RetryOnchainEvents_Handler,
		},
		{
			MethodName: "RetryFnameEvents",
			Handler:    _AdminService_RetryFnameEvents_Handler,
		},
		{
			MethodName: "RunOnchainEventsMigration",
			Handler:    _AdminService_RunOnchainEventsMigration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_rpc.proto",
}
